package com.example.startProject.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Person {
	
	//id to be generated by db
	private Integer id; 
	private String firstName;
	private String lastName;
	private Integer age;
	private String dob;
	

}
