package com.example.startProject.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@Table(name = "person_tab")
public class Person {
	
	//id to be generated by db
	private Integer id; 
	
	//conerts camel case to sepearted words with underscore
	//firstName - first_name
	private String firstName;
	
	@Column(name = "ln")
	private String lastName;
	
	private Integer age;
	private String dob;
	

}
